name: Fast API docker build push
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos a ejecutar
    # En las pruebas
    - uses: actions/checkout@v3

    - name: Check tests status
      run: python app/test_utils.py

    - name: Build the FastAPI Docker image
      run: docker build -t '${{secrets.DOCKER_LOGIN}}'/fastapi-docker-workflow:'${{github.sha}}' .
      
    - name: Login to docker
      run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: Push the docker image
      run: docker push '${{secrets.DOCKER_LOGIN}}'/fastapi-docker-workflow:'${{github.sha}}'
  nothing:
    runs-on: ubuntu-latest
    steps:
    - name: just do nothing bro!
      run: echo "i'm doing nothing!" > nothing_to_read.txt